/* asm_grcore.c: link stubs for the assembly module src/gfx/GRCORE.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char Color_data_ptr[0x8] STUB_ALIGN;  /* int16 * */
unsigned char background_color[0x8] STUB_ALIGN;  /* unsigned char * */
void box(void) { port_stub("box"); }  /* void (int, int, int, int) */
unsigned char bytefont[0x8] STUB_ALIGN;  /* unsigned char * */
void clear_window(void) { port_stub("clear_window"); }  /* void (void) */
void copy_hidden_to_visible(void) { port_stub("copy_hidden_to_visible"); }  /* void (void) */
void copy_visible_to_hidden(void) { port_stub("copy_visible_to_hidden"); }  /* void (void) */
unsigned char cur_font[0x8] STUB_ALIGN;  /* struct FontInfo * */
void fbshow(void) { port_stub("fbshow"); }  /* void (void *, int, int, int, int) */
void fbuf_setcolor(void) { port_stub("fbuf_setcolor"); }  /* void (int) */
unsigned char foreground_color[0x8] STUB_ALIGN;  /* unsigned char * */
void grPageFlip(void) { port_stub("grPageFlip"); }  /* void (void) */
void grSoftPageFlip(void) { port_stub("grSoftPageFlip"); }  /* void (void) */
void gr_read_pixel(void) { port_stub("gr_read_pixel"); }  /* unsigned char (int, int) */
void init_colors(void) { port_stub("init_colors"); }  /* void (void) */
void init_graphics(void) { port_stub("init_graphics"); }  /* void (void) */
unsigned char palette[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char pixel_color[0x8] STUB_ALIGN;  /* unsigned char * */
void rectangle(void) { port_stub("rectangle"); }  /* void (int, int, int, int) */
void seg003_581E(void) { port_stub("seg003_581E"); }  /* void (int, int, int, int, int, int, int) */
void set_the_color(void) { port_stub("set_the_color"); }  /* void (int) */
void set_the_window(void) { port_stub("set_the_window"); }  /* void (int, int, int, int) */
void setup_font(void) { port_stub("setup_font"); }  /* void (void) */
void show(void) { port_stub("show"); }  /* void (int, int, unsigned char *, int, int, int, int) */
void string_to_screen(void) { port_stub("string_to_screen"); }  /* void (char *, int, int) */
void string_width(void) { port_stub("string_width"); }  /* int (char *) */
void uhline(void) { port_stub("uhline"); }  /* void (int, int, int) */
void vcopy(void) { port_stub("vcopy"); }  /* void (int, int, int, int, int, int) */
void vcopyfb(void) { port_stub("vcopyfb"); }  /* void (int, int, int, int, int) */
unsigned char wbot[0x8] STUB_ALIGN;  /* int16 * */
unsigned char wleft[0x8] STUB_ALIGN;  /* int16 * */
unsigned char wright[0x8] STUB_ALIGN;  /* int16 * */
unsigned char wtop[0x8] STUB_ALIGN;  /* int16 * */
