/* asm_valloc.c: link stubs for the assembly module src/gfx/VALLOC.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void restore_rect(void) { port_stub("restore_rect"); }  /* void (int) */
void save_rect(void) { port_stub("save_rect"); }  /* void (int, int, int, int, int) */
void seg001_023B_C(void) { port_stub("seg001_023B_C"); }  /* void (void) */
void valloc(void) { port_stub("valloc"); }  /* int (int, int) */
void vfree(void) { port_stub("vfree"); }  /* void (int) */
