/* asm_lpfdelta.c: link stubs for the assembly module src/gfx/LPFDELTA.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void seg002_A(void) { port_stub("seg002_A"); }  /* void (unsigned char *, unsigned char *) */
