/* asm_c3dentry.c: link stubs for the assembly module src/sys/C3DENTRY.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void cAtan2(void) { port_stub("cAtan2"); }  /* int (int, int) */
unsigned char cDbase[0x8] STUB_ALIGN;  /* int16 * */
unsigned char cDbbase[0x8] STUB_ALIGN;  /* int16 * */
unsigned char cEntryStrt[0x8] STUB_ALIGN;  /* int16 * */
void cFBtoScreen(void) { port_stub("cFBtoScreen"); }  /* void (void) */
void cFillFB(void) { port_stub("cFillFB"); }  /* void (int) */
void cFrmtoRaw(void) { port_stub("cFrmtoRaw"); }  /* void *(void *, unsigned char *, unsigned char) */
void cFstSinCos(void) { port_stub("cFstSinCos"); }  /* void (int, int16 *, int16 *) */
void cInit3d(void) { port_stub("cInit3d"); }  /* void (void) */
unsigned char cLightTabs[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char cPixXferStuff[0x8] STUB_ALIGN;  /* int16 * */
void cPlaceFB(void) { port_stub("cPlaceFB"); }  /* void (int, int, int, int) */
unsigned char cPlayer[0x8] STUB_ALIGN;  /* struct Camera * */
void cRender(void) { port_stub("cRender"); }  /* void (void) */
void cSinCos(void) { port_stub("cSinCos"); }  /* void (int, int16 *, int16 *) */
void cSqRt(void) { port_stub("cSqRt"); }  /* int (int32) */
void cZoom(void) { port_stub("cZoom"); }  /* void (unsigned int) */
void seg019_CB7(void) { port_stub("seg019_CB7"); }  /* void (int) */
void seg019_CEA(void) { port_stub("seg019_CEA"); }  /* void (int) */
