/* asm_setpnt.c: link stubs for the assembly module src/3d/SETPNT.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void SetPnt(void) { port_stub("SetPnt"); }  /* int (char, char, char) */
