/* borland.c: link stubs for Borland's C library (the port's stand-in headers and compat.h).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void delay(void) { port_stub("delay"); }  /* void (unsigned int) */
void int86(void) { port_stub("int86"); }  /* int (int, union REGS *, union REGS *) */
void nosound(void) { port_stub("nosound"); }  /* void (void) */
void sound(void) { port_stub("sound"); }  /* void (unsigned int) */
