/* portlayer.c: link stubs for the portability layer's own names (port_ and bc_, compat.h and portable.h).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void port_render_tag(void) { port_stub("port_render_tag"); }  /* void (const void *, const void *) */
