/* asm_fardata.c: link stubs for the assembly module src/sys/FARDATA.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char cmpbuf1_start[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char dfx_buffer[0x10000] STUB_ALIGN;  /* char[] */
unsigned char seg_5DFD[0x10000] STUB_ALIGN;  /* unsigned char[] */
