/* asm_sprite.c: link stubs for the assembly module src/gfx/SPRITE.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void change_sprite(void) { port_stub("change_sprite"); }  /* void (int, int, int, int, int) */
void create_sprite(void) { port_stub("create_sprite"); }  /* int (int, ...) */
void draw_mask(void) { port_stub("draw_mask"); }  /* void (int, int) */
void draw_sprite(void) { port_stub("draw_sprite"); }  /* void (int, int) */
void erase_sprite(void) { port_stub("erase_sprite"); }  /* void (int) */
void move_sprite(void) { port_stub("move_sprite"); }  /* void (int, int, int) */
void set_yoff(void) { port_stub("set_yoff"); }  /* void (int, int) */
void update_sprites(void) { port_stub("update_sprites"); }  /* void (void) */
