/* asm_pgcache.c: link stubs for the assembly module src/3d/PGCACHE.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char grs_off[0x8] STUB_ALIGN;  /* uint16 * */
unsigned char obj_tab[0x8] STUB_ALIGN;  /* uint16 * */
