/* asm_int0trap.c: link stubs for the assembly module src/sys/INT0TRAP.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char int0_sp[0x2] STUB_ALIGN;  /* uint16 */
unsigned char int0_ss[0x2] STUB_ALIGN;  /* uint16 */
void int0_trap(void) { port_stub("int0_trap"); }  /* void () */
