/* asm_modex.c: link stubs for the assembly module src/gfx/MODEX.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void DRAW_RELATED_seg017_2179_2A2(void) { port_stub("DRAW_RELATED_seg017_2179_2A2"); }  /* void (unsigned char *, unsigned int, int, int) */
void DRAW_RELATED_seg017_2179_320(void) { port_stub("DRAW_RELATED_seg017_2179_320"); }  /* void (unsigned int, int16 *, int16 *) */
void DRAW_RELATED_seg017_2179_361(void) { port_stub("DRAW_RELATED_seg017_2179_361"); }  /* int (unsigned char *, unsigned int, int) */
void FindStringDelimiter(void) { port_stub("FindStringDelimiter"); }  /* char *(char *, int) */
void PrintStringToConsole_seg017_DE(void) { port_stub("PrintStringToConsole_seg017_DE"); }  /* void (char *) */
void gr_pixel(void) { port_stub("gr_pixel"); }  /* void (int, int, int) */
void grab(void) { port_stub("grab"); }  /* void (void *, int, int, int, int) */
void local_do_palette(void) { port_stub("local_do_palette"); }  /* void (int, unsigned char) */
void mem_set(void) { port_stub("mem_set"); }  /* void (void *, int, int) */
void str_cmp(void) { port_stub("str_cmp"); }  /* int (char *, char *) */
void str_copy(void) { port_stub("str_copy"); }  /* char *(char *, char *) */
void str_len(void) { port_stub("str_len"); }  /* int (char *) */
void str_ncopy(void) { port_stub("str_ncopy"); }  /* void (char *, char *, int) */
void str_str(void) { port_stub("str_str"); }  /* char *(char *, char *) */
