/* asm_scalebm.c: link stubs for the assembly module src/gfx/SCALEBM.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char ShowClip[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char Transparency[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char cXfer[0x10000] STUB_ALIGN;  /* unsigned char[] */
