/* asm_sysentry.c: link stubs for the assembly module src/sys/SYSENTRY.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char Alt[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char Asc[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char CapsLock[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char Ctrl[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char MouseDx[0x8] STUB_ALIGN;  /* int16 * */
unsigned char MouseDy[0x8] STUB_ALIGN;  /* int16 * */
unsigned char MouseOn[0x8] STUB_ALIGN;  /* int16 * */
unsigned char Shift[0x8] STUB_ALIGN;  /* unsigned char * */
unsigned char Time[0x8] STUB_ALIGN;  /* uint32 * */
unsigned char cExitMessage[0x8] STUB_ALIGN;  /* char * */
unsigned char cJoyInit[0x8] STUB_ALIGN;  /* int16 * */
unsigned char cPerror[0x8] STUB_ALIGN;  /* int16 * */
unsigned char joy_buttons[0x8] STUB_ALIGN;  /* int16 * */
unsigned char joy_position[0x8] STUB_ALIGN;  /* int16 * */
void key(void) { port_stub("key"); }  /* int (void) */
unsigned char key_on[0x8] STUB_ALIGN;  /* unsigned char * */
void mbuttons(void) { port_stub("mbuttons"); }  /* int (void) */
void mouse(void) { port_stub("mouse"); }  /* void (void) */
void seg021_22FD_755(void) { port_stub("seg021_22FD_755"); }  /* void (void) */
void seg021_22FD_791(void) { port_stub("seg021_22FD_791"); }  /* void (void) */
void seg021_22FD_7CD(void) { port_stub("seg021_22FD_7CD"); }  /* void (void) */
void seg021_22FD_809(void) { port_stub("seg021_22FD_809"); }  /* void (void) */
