/* asm_modex.c: link stubs for the assembly module src/gfx/MODEX.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void grab(void) { port_stub("grab"); }  /* void (void *, int, int, int, int) */
