/* asm_grcore.c: link stubs for the assembly module src/gfx/GRCORE.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void box(void) { port_stub("box"); }  /* void (int, int, int, int) */
void copy_hidden_to_visible(void) { port_stub("copy_hidden_to_visible"); }  /* void (void) */
void copy_visible_to_hidden(void) { port_stub("copy_visible_to_hidden"); }  /* void (void) */
void fbshow(void) { port_stub("fbshow"); }  /* void (void *, int, int, int, int) */
void fbuf_setcolor(void) { port_stub("fbuf_setcolor"); }  /* void (int) */
void gr_read_pixel(void) { port_stub("gr_read_pixel"); }  /* unsigned char (int, int) */
void plot_pixel(void) { port_stub("plot_pixel"); }  /* void (int, int) */
void seg003_0272_4A3A(void) { port_stub("seg003_0272_4A3A"); }  /* void (int, int, int) */
void seg003_0272_5025(void) { port_stub("seg003_0272_5025"); }  /* void (int, int, int, int, int, int, int) */
void string_to_screen(void) { port_stub("string_to_screen"); }  /* void (char *, int, int) */
void string_width(void) { port_stub("string_width"); }  /* int (char *) */
void uhline(void) { port_stub("uhline"); }  /* void (int, int, int) */
void uvline(void) { port_stub("uvline"); }  /* void (int, int, int) */
void vcopy(void) { port_stub("vcopy"); }  /* void (int, int, int, int, int, int) */
void vcopyfb(void) { port_stub("vcopyfb"); }  /* void (int, int, int, int, int) */
void vscreen_focus(void) { port_stub("vscreen_focus"); }  /* void (int, int) */
