/* asm_tmapops.c: link stubs for the assembly module src/3d/TMAPOPS.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char CmapCache[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char CmapFrm[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char CmaptoPg[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char EmsBuff[0x2] STUB_ALIGN;  /* uint16 */
unsigned char PgtoCmap[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char crit_fpage[0x2] STUB_ALIGN;  /* uint16 */
unsigned char crit_inpage[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char crit_nlpages[0x2] STUB_ALIGN;  /* uint16 */
unsigned char first_anim[0x2] STUB_ALIGN;  /* uint16 */
unsigned char grs_3dinf[0x10000] STUB_ALIGN;  /* struct Grs3d[] */
unsigned char obj_inpage1[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char scrgr_fpage[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char tmap_fpage[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char tmap_inpage[0x1] STUB_ALIGN;  /* unsigned char */
