/* asm_overlay.c: link stubs for the assembly module src/lib/OVERLAY.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void _OvrInitEms(void) { port_stub("_OvrInitEms"); }  /* int (unsigned int, unsigned int, unsigned int) */
