/* asm_ail.c: link stubs for the assembly module src/sound/AIL.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void AIL_default_timbre_cache_size(void) { port_stub("AIL_default_timbre_cache_size"); }  /* unsigned int (int) */
void AIL_define_timbre_cache(void) { port_stub("AIL_define_timbre_cache"); }  /* void (int, void *, unsigned int) */
void AIL_describe_driver(void) { port_stub("AIL_describe_driver"); }  /* struct DrvrDesc *(int) */
void AIL_detect_device(void) { port_stub("AIL_detect_device"); }  /* int (int, int, int, int, int) */
void AIL_index_VOC_block(void) { port_stub("AIL_index_VOC_block"); }  /* int (int, void *, int, struct SoundBuff *) */
void AIL_init_driver(void) { port_stub("AIL_init_driver"); }  /* void (int, int, int, int, int) */
void AIL_install_timbre(void) { port_stub("AIL_install_timbre"); }  /* void (int, int, int, void *) */
void AIL_lock_channel(void) { port_stub("AIL_lock_channel"); }  /* int (int) */
void AIL_pause_digital_playback(void) { port_stub("AIL_pause_digital_playback"); }  /* void (int) */
void AIL_register_driver(void) { port_stub("AIL_register_driver"); }  /* int (void *) */
void AIL_register_sequence(void) { port_stub("AIL_register_sequence"); }  /* int (int, void *, int, void *, void *) */
void AIL_register_sound_buffer(void) { port_stub("AIL_register_sound_buffer"); }  /* void (int, int, struct SoundBuff *) */
void AIL_register_timer(void) { port_stub("AIL_register_timer"); }  /* int (void (*)(void)) */
void AIL_release_channel(void) { port_stub("AIL_release_channel"); }  /* void (int, int) */
void AIL_release_sequence_handle(void) { port_stub("AIL_release_sequence_handle"); }  /* void (int, int) */
void AIL_release_timer_handle(void) { port_stub("AIL_release_timer_handle"); }  /* void (int) */
void AIL_resume_digital_playback(void) { port_stub("AIL_resume_digital_playback"); }  /* void (int) */
void AIL_send_channel_voice_message(void) { port_stub("AIL_send_channel_voice_message"); }  /* void (int, int, int, int) */
void AIL_sequence_status(void) { port_stub("AIL_sequence_status"); }  /* unsigned int (int, int) */
void AIL_set_digital_playback_panpot(void) { port_stub("AIL_set_digital_playback_panpot"); }  /* void (int, int) */
void AIL_set_digital_playback_volume(void) { port_stub("AIL_set_digital_playback_volume"); }  /* void (int, int) */
void AIL_set_relative_tempo(void) { port_stub("AIL_set_relative_tempo"); }  /* void (int, int, int, int) */
void AIL_set_relative_volume(void) { port_stub("AIL_set_relative_volume"); }  /* void (int, int, int, int) */
void AIL_set_timer_frequency(void) { port_stub("AIL_set_timer_frequency"); }  /* void (int, uint32) */
void AIL_shutdown(void) { port_stub("AIL_shutdown"); }  /* void (char *) */
void AIL_shutdown_driver(void) { port_stub("AIL_shutdown_driver"); }  /* void (int, char *) */
void AIL_sound_buffer_status(void) { port_stub("AIL_sound_buffer_status"); }  /* unsigned int (int, int) */
void AIL_start_digital_playback(void) { port_stub("AIL_start_digital_playback"); }  /* void (int) */
void AIL_start_sequence(void) { port_stub("AIL_start_sequence"); }  /* void (int, int) */
void AIL_start_timer(void) { port_stub("AIL_start_timer"); }  /* void (int) */
void AIL_startup(void) { port_stub("AIL_startup"); }  /* void (void) */
void AIL_state_table_size(void) { port_stub("AIL_state_table_size"); }  /* unsigned int (int) */
void AIL_stop_digital_playback(void) { port_stub("AIL_stop_digital_playback"); }  /* void (int) */
void AIL_stop_sequence(void) { port_stub("AIL_stop_sequence"); }  /* void (int, int) */
void AIL_stop_timer(void) { port_stub("AIL_stop_timer"); }  /* void (int) */
void AIL_timbre_request(void) { port_stub("AIL_timbre_request"); }  /* unsigned int (int, int) */
void AIL_timbre_status(void) { port_stub("AIL_timbre_status"); }  /* int (int, int, int) */
