/* borland.c: link stubs for Borland's C library (the port's stand-in headers and compat.h).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char _ctype[0x10000] STUB_ALIGN;  /* unsigned char[] */
void coreleft(void) { port_stub("coreleft"); }  /* unsigned int (void) */
void eof(void) { port_stub("eof"); }  /* int (int) */
void farcoreleft(void) { port_stub("farcoreleft"); }  /* unsigned long (void) */
void farfree(void) { port_stub("farfree"); }  /* void (void *) */
void farmalloc(void) { port_stub("farmalloc"); }  /* void *(unsigned long) */
void filelength(void) { port_stub("filelength"); }  /* long (int) */
void findfirst(void) { port_stub("findfirst"); }  /* int (const char *, struct ffblk *, int) */
void findnext(void) { port_stub("findnext"); }  /* int (struct ffblk *) */
void getcurdir(void) { port_stub("getcurdir"); }  /* int (int, char *) */
void getdfree(void) { port_stub("getdfree"); }  /* void (unsigned char, struct dfree *) */
void getvect(void) { port_stub("getvect"); }  /* void (*(int))() */
void intdosx(void) { port_stub("intdosx"); }  /* int (union REGS *, union REGS *, struct SREGS *) */
void itoa(void) { port_stub("itoa"); }  /* char *(int, char *, int) */
void ltoa(void) { port_stub("ltoa"); }  /* char *(long, char *, int) */
void movedata(void) { port_stub("movedata"); }  /* void (unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) */
void outportb(void) { port_stub("outportb"); }  /* void (unsigned int, unsigned char) */
void setvect(void) { port_stub("setvect"); }  /* void (int, void (*)()) */
void strnicmp(void) { port_stub("strnicmp"); }  /* int (const char *, const char *, size_t) */
void strupr(void) { port_stub("strupr"); }  /* char *(char *) */
void tell(void) { port_stub("tell"); }  /* long (int) */
