/* dgroup.c: link stubs for the DGROUP gaps tools/extract.py places (data no C source defines yet).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char CutsceneOrConversationStringBlock[0x2] STUB_ALIGN;  /* int16 */
unsigned char Inventory[0x38] STUB_ALIGN;  /* union Link[28] */
unsigned char StringsPak_Address_Indices[0x8] STUB_ALIGN;  /* struct StringNode * */
unsigned char StringsPak_FileHandle[0x8] STUB_ALIGN;  /* FILE * */
unsigned char StringsPak_NoOfNodes[0x2] STUB_ALIGN;  /* int16 */
unsigned char curelem[0x8] STUB_ALIGN;  /* struct Object * */
unsigned char string_bits[0x2] STUB_ALIGN;  /* int16 */
