/* dosonly_ems.c: link stubs for the DOS-only C file src/sys/EMS.C.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void MapMemory_seg013_1D3C_C7(void) { port_stub("MapMemory_seg013_1D3C_C7"); }  /* char (char, unsigned int) */
unsigned char ems_frame[0x2] STUB_ALIGN;  /* uint16 */
void seg013_1D3C_A(void) { port_stub("seg013_1D3C_A"); }  /* int (unsigned int, unsigned int) */
void seg013_1D3C_B2(void) { port_stub("seg013_1D3C_B2"); }  /* void (void) */
void seg013_1D3C_E4(void) { port_stub("seg013_1D3C_E4"); }  /* unsigned char (unsigned int, unsigned int, int) */
