/* exedata.c: link stubs for the far data tools/extract.py takes from UW2.EXE (renderer tables, model data, stdat and the names inside it).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char ATM_Strings[0x1518] STUB_ALIGN;  /* struct ATM[100] */
unsigned char ModelData_seg052_519C_2600[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char _dblen[0x2] STUB_ALIGN;  /* int16 */
unsigned char bmhgtoff[0x2] STUB_ALIGN;  /* uint16 */
unsigned char bmsegoff[0x2] STUB_ALIGN;  /* uint16 */
unsigned char cmpbuf2_start[0x10000] STUB_ALIGN;  /* unsigned char[] */
unsigned char gr_offs[0x10000] STUB_ALIGN;  /* uint32[] */
unsigned char smooth_base[0x2] STUB_ALIGN;  /* int16 */
unsigned char smooth_div[0x2] STUB_ALIGN;  /* int16 */
unsigned char smooth_lowpass[0x2] STUB_ALIGN;  /* int16 */
unsigned char sound_fpage[0x1] STUB_ALIGN;  /* unsigned char */
unsigned char stdat[0x10000] STUB_ALIGN;  /* unsigned char[] */
