/* exedata.c: link stubs for the far data tools/extract.py takes from UW2.EXE (renderer tables, model data, stdat and the names inside it).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

unsigned char sound_fpage[0x1] STUB_ALIGN;  /* unsigned char */
