/* portlayer.c: link stubs for the portability layer's own names (port_ and bc_, compat.h and portable.h).
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and aborts; each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void bc_access(void) { port_stub("bc_access"); }  /* int (const char *, int) */
void bc_chdir(void) { port_stub("bc_chdir"); }  /* int (const char *) */
void bc_close(void) { port_stub("bc_close"); }  /* int (int) */
void bc_fopen(void) { port_stub("bc_fopen"); }  /* FILE *(const char *, const char *) */
void bc_fstat(void) { port_stub("bc_fstat"); }  /* int (int, struct stat *) */
void bc_geninterrupt(void) { port_stub("bc_geninterrupt"); }  /* void (int) */
void bc_lseek(void) { port_stub("bc_lseek"); }  /* long (int, long, int) */
void bc_mkdir(void) { port_stub("bc_mkdir"); }  /* int (const char *) */
void bc_open(void) { port_stub("bc_open"); }  /* int (const char *, int, ...) */
void bc_rand(void) { port_stub("bc_rand"); }  /* int (void) */
void bc_read(void) { port_stub("bc_read"); }  /* int (int, void *, unsigned int) */
void bc_srand(void) { port_stub("bc_srand"); }  /* void (unsigned int) */
void bc_stat(void) { port_stub("bc_stat"); }  /* int (const char *, struct stat *) */
void bc_time(void) { port_stub("bc_time"); }  /* long (long *) */
void bc_unlink(void) { port_stub("bc_unlink"); }  /* int (const char *) */
void bc_write(void) { port_stub("bc_write"); }  /* int (int, const void *, unsigned int) */
void port_far_copy(void) { port_stub("port_far_copy"); }  /* void (void *, const void *, unsigned int) */
void port_fp_off(void) { port_stub("port_fp_off"); }  /* unsigned int (const volatile void *) */
void port_fp_seg(void) { port_stub("port_fp_seg"); }  /* unsigned int (const volatile void *) */
void port_mk_fp(void) { port_stub("port_mk_fp"); }  /* void *(unsigned int, unsigned int) */
void port_null_far(void) { port_stub("port_null_far"); }  /* void *(const char *, int) */
void port_null_near(void) { port_stub("port_null_near"); }  /* void *(const char *, int) */
unsigned char port_sp[0x2] STUB_ALIGN;  /* uint16_t */
unsigned char port_ss[0x2] STUB_ALIGN;  /* uint16_t */
