/* asm_sysentry.c: link stubs for the assembly module src/sys/SYSENTRY.ASM.
   Generated by tools/portstubs.py; do not edit by hand.
   Each function reports itself and stops the game there (port_stub); each variable is zeroed storage of its
   declared size. A real replacement takes these names out of this file. */
#include "stub.h"

void seg021_22FD_7CD(void) { port_stub("seg021_22FD_7CD"); }  /* void (void) */
void seg021_22FD_809(void) { port_stub("seg021_22FD_809"); }  /* void (void) */
